---
title: "Data Scientist Skills"
author: "Marley Myrianthopoulos"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyr)
library(tidyverse)
library(dplyr)

data_scientist_skills_list <- read.csv("https://raw.githubusercontent.com/samato0624/DATA607_Project3/main/docs/data_scientist_skills.csv")

data_scientist_skills_list <- data_scientist_skills_list[-1,]

unique_skills_list <- data.frame(skills_list = unlist(data_scientist_skills_list))

unique_skills_list <- unique_skills_list %>%
  filter(skills_list != "") %>%
  group_by(skills_list) %>%
  mutate(count = length(skills_list)) %>%
  distinct(skills_list,count) %>%
  arrange(desc(count), skills_list)
  
rownames(unique_skills_list) <- NULL

final_skills_list <- unique_skills_list[c(1:9,12,13,17,19,22,24,27:29,32,34,36:37,39,40,43,45,47:50,52,53,58,59,61,62,64,66,71,72,76,77,79:81,83:87),1]

final_skills_list <- final_skills_list %>% arrange(skills_list)

final_skills_list$skills_list <- tolower(final_skills_list$skills_list)

final_skills_list$skills_list[38] <- " r "

final_skills_list

```

```{r}

raw_data <- read.csv("https://raw.githubusercontent.com/samato0624/DATA607_Project3/main/Raw_Data.csv")

skills <- raw_data %>%
  mutate(Pay.Range = (str_remove_all(Pay.Range, "[$yr////, ]"))) %>%
  mutate(Pay_Min = as.numeric(str_extract(Pay.Range, "\\d+(?=-)"))) %>%
  mutate(Pay_Max = as.numeric(str_extract(Pay.Range, "(?<=-)[0-9]+"))) %>%
  select(c(2, 3, 5, 6, 7, 8))

skills

```

```{r}

skills_data <- final_skills_list


for(i in 1:nrow(skills_data)) {
  skills_data$postings[i] <- as.numeric(skills %>% filter(str_detect(tolower(About.the.job),skills_data$skills_list[i])) %>% summarise(n = n()))
}

skills_data <- skills_data %>% filter(postings != 0)

for(i in 1:nrow(skills_data)) {
  skills_data$avg_min_sal[i] <- as.numeric(skills %>% drop_na(Pay_Min) %>% filter(str_detect(tolower(About.the.job),skills_data$skills_list[i])) %>% summarise(avg = mean(Pay_Min)))
}

skills_data_postings <- skills_data %>% arrange(desc(postings))
skills_data_postings

skills_data_sal <- skills_data %>% filter(postings >= 5) %>% arrange(desc(avg_min_sal))
skills_data_sal



```
